### ISSUE TITLE
Adicionar README.md

### ISSUE THREAD

**Issue by IvoPereira** [devpt-org/discord-bot#19]
O projeto atual deveria ter um ficheiro `README.md` que explique o conceito do bot.

Para além de uma introdução básica do projeto, seria benéfico ter também no README:
- instruções para desenvolvimento local (ainda não implementado)
- instruções da execução de testes (ainda não implementado)

**Comment by Alf0nso** [comment]
Ainda nao temos readme.
Hoje (Nov 18 2022) vais fazer stream certo? 
Se calhar o README e instruções para desenvolvimento local deveriam ser prioridade?

ps: este issue foi escrito com teclado estrangeiro dai os erros de acentuação...

**Comment by IvoPereira** [comment]
O README.md deveria ter instruções para desenvolvimento local sim, e ter um pequeno parágrafo explicativo sobre o que é o projeto (adicionei no repo de Github se ajudar).

É também importante ter uma referência aos docs de arquitetura.

Talvez até o @zorkpt ou o @Adjilino se tiverem interesse possam enviar umas ideias aqui tendo em conta que têm enviado alguns commits recentemente?

**Comment by Adjilino** [comment]
Posso tentar, não sou muito bom a explicar 😅

**Comment by joaojesus81** [comment]
@Alf0nso este issue ainda esta aberto? depois de uma vista de olhos rapida parece me que a maior parte do texto necessario para um README e/ou CONTRIBUTING_GUIDE ja esta no ARCHITECTURE. Nao me importo de pegar nisto e pegar em algumas partes do ARCHITECTURE para criar README e CONTRIBUTING_GUIDE se ainda for necessario.

**Comment by Alf0nso** [comment]
@joaojesus81 Sim, está! Efectivamente acabou-se por não se fazer um README, se tens tempo e vontade estamos completamente abertos a um pull request :)
