### ISSUE TITLE
Implementar conventional commits

### ISSUE THREAD

**Issue by IvoPereira** [devpt-org/discord-bot#50]
Para que os commits passem a ficar uniformes, seria interessante implementarmos um enforcer de conventional commits:

https://www.conventionalcommits.org/en/v1.0.0/

**Comment by raulcorreia7** [comment]
Resolvido,

A minha sugestão é usar [commitlint](https://commitlint.js.org/#/)
Usei o [exemplo de Typescript](https://commitlint.js.org/#/reference-configuration?id=typescript)


Apenas usar o default extend é suficiente.

Nota: Ao brincar com a configuração notei que faz override ao default e não apanha tudo.

**Comment by IvoPereira** [comment]
Closed by https://github.com/devpt-org/discord-bot/pull/60.
